name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pipeline:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      COMPOSER_NO_INTERACTION: 1

    steps:
      ###################
      # Stage 1 - Build #
      ###################
      - name: Start Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: start-measurement

      - name: Checkout latest revision
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: pcov
          tools: composer:v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Checkout Repo Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: get-measurement
          label: 'build'

      ###########################
      # Stage 2 - Code Analysis #
      ###########################
      - name: Code Style Fixer
        run: vendor/bin/php-cs-fixer fix src --dry-run

      - name: Static Code Analysis
        run: vendor/bin/phpstan

      - name: Checkout Repo Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: get-measurement
          label: 'code analysis'


      ###################
      # Stage 3 - Tests #
      ###################
      - name: Unit Tests
        run: php -d pcov.enabled=1 vendor/bin/phpunit --coverage-clover=tests/coverage.xml

      - if: ${{ github.event_name == 'pull_request' }}
        name: Download artifact
        uses: dawidd6/action-download-artifact@v6
        continue-on-error: true
        with:
          workflow: .github/workflows/ci.yml
          branch: main
          name: coverage-report
          path: tests/base

      - if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: tests/coverage.xml

      - if: ${{ github.event_name == 'pull_request' }}
        name: Coverage Report as Comment (Clover)
        uses: lucassabreu/comment-coverage-clover@main
        with:
          file: coverage.xml
          base-file: tests/base/coverage.xml

      - name: Checkout Repo Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: get-measurement
          label: 'tests'

      - name: Show Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4

        with:
          task: display-results